In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

from sklearn import datasets

wine = datasets.load_wine()

X = wine.data
y = wine.target

In [9]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X, y, test_size = 0.3)

In [18]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=9)

knn.fit(X_train , y_train)

y_pred = knn.predict(X_test)

In [19]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test , y_pred))

[[19  0  1]
 [ 1 14  5]
 [ 4  4  6]]
              precision    recall  f1-score   support

           0       0.79      0.95      0.86        20
           1       0.78      0.70      0.74        20
           2       0.50      0.43      0.46        14

    accuracy                           0.72        54
   macro avg       0.69      0.69      0.69        54
weighted avg       0.71      0.72      0.71        54



In [20]:
print("Accuracy Score : ",accuracy_score(y_test , y_pred))

Accuracy Score :  0.7222222222222222
